[package]
name = "cargo-stopwatchd"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
atomic-time = "0.1.5"
clap = "4.5.40"
discord-presence = "3.0"
serde_json = "1.0.140"
stopwatch-protocol = { path = "../stopwatch-protocol"}
tokio = { version = "1.45.1", features = ["full"] }
